// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkVBMda_z-hRK-yxqrUox5JCF1cO0FsKI',
    appId: '1:963514549159:web:0c3d9132270a1791bb6c82',
    messagingSenderId: '963514549159',
    projectId: 'sodaimart-421115',
    authDomain: 'sodaimart-421115.firebaseapp.com',
    storageBucket: 'sodaimart-421115.firebasestorage.app',
    measurementId: 'G-VPWJ4VYVFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFDXD1Aq_uAqshADhKlm970Au1hq7qxSM',
    appId: '1:963514549159:android:2b546ee03dec70cfbb6c82',
    messagingSenderId: '963514549159',
    projectId: 'sodaimart-421115',
    storageBucket: 'sodaimart-421115.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxEarg7rj4NjY9r8ekvHSSv6Gnayks4No',
    appId: '1:963514549159:ios:57334480bae0b97bbb6c82',
    messagingSenderId: '963514549159',
    projectId: 'sodaimart-421115',
    storageBucket: 'sodaimart-421115.firebasestorage.app',
    iosBundleId: 'com.example.taskManagerTask',
  );
}
